FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    gcc \
    g++ \
    python3 \
    python3-pip \
    openjdk-17-jdk \
    nodejs \
    npm \
    && apt-get clean

WORKDIR /sandbox

CMD ["bash"]